language: c
addons:
  apt:
    packages:
    - ocaml-nox
    - ocaml-findlib

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y ladspa-sdk

script: ./bootstrap && ./configure && make && make -C examples
